name: CI/CD

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: клонирование
        uses: actions/checkout@v3

      - name: вход
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NAME }}
          password: ${{ secrets.PASSWORD }}

      - name: сборка
        run: docker build -t ${{ secrets.NAME }}/kanban-frontend:latest 

      - name: отправка
        run: docker push ${{ secrets.NAME }}/kanban-frontend:latest